### ISSUE TITLE
Auto import for ES module as well

### ISSUE THREAD

**Issue by princescar** [brillout/vite-plugin-server-entry#13]
Can we use `import.meta.filename` for ES module and leave `__dirname` for CJS so that auto import also works for ES module?

**Comment by princescar** [comment]
This is for this package, I'm setting up a project with Vike and Hattip, in ES module format. The server entry is generated but cannot be automatically imported due the the issue I mentioned.

https://github.com/brillout/vite-plugin-server-entry/blob/1c71c489d9fe06d716ccb022756b2274e94837c3/src/runtime/crawlServerEntry.ts#L45
```typescript
  let filename: string
  try {
    filename = __filename
  } catch {
    // __filename isn't defined when this file is being bundled into an ESM bundle
    return false
  }
```

Though manual import is ok as a workaround, it's not neat as I need to append the following to hattip entry.

```typescript
if (getEnvVar("NODE_ENV", "development") === "production") {
  // Use variable to cheat the build check.
  const serverEntryPoint = "./entry.mjs";
  await import(serverEntryPoint);
}
```

So I'm wondering if we can improve this package to make the auto import also work in ES module?

**Comment by brillout** [comment]
Fix released in `0.5.2`. I didn't try it and maybe using `import.meta.url` instead is needed (it would actually be better in order to support older Node.js versions). Let me know if doesn't work or PR welcome.

**Comment by brillout** [comment]
I've reverted the fix, but I went for another fix. Try `0.5.4`.

**Comment by princescar** [comment]
Tested it, and it works fine in my project! I appreciate the timely response!
